name: Test and deploy BETHA to Azure VM

on:
  push:
    branches:
      - main
    paths:
      - './github/workflows/deploy.yml'
      - 'src/**'
      - 'test/**'
      - 'package.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npx jest --verbose --coverage --coverageReporters=text --coverageReporters=none

