# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node, then deploy them to Azure
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test and deploy BETHA to Azure VM

on:
  push:
    branches:
      - main
    paths:
      - './github/workflows/deploy.yml'
      - 'src/**'
      - 'test/**'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci

    - name: Test
      run: npx jest --verbose --coverage --coverageReporters=text --coverageReporters=none
